apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  db-url: mongodb://mongo:30017/?directConnection=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dep
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gaonengwww/k8s-real-combat-server
          imagePullPolicy: IfNotPresent
          args: ["dist/apps/user/main"]
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              value: 'mongodb://mongo:30017/?directConnection=true'
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: gaonengwww/k8s-real-combat-server
          imagePullPolicy: IfNotPresent
          args: ["dist/apps/user/main"]
          env:
            - name: db-url
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: db-url